### ISSUE TITLE
[BUG]: le label non si attivano

### ISSUE THREAD

**Issue by antenucci96** [italia/design-angular-kit#277]
## Comportamento atteso
La label dovrebbe spostarsi all'inserimento del testo

## Comportamento attuale
La label non si sposta
![Peek 2023-10-13 10-55](https://github.com/italia/design-angular-kit/assets/60515229/27dbb10b-c4a4-44d0-a50d-e5df6658b88b)

## Possibili soluzioni
Al momento ho risolto con questo in un ng-deep :
```scss
 .form-group label.active {
    transform: translateY(-75%);
  }
``` 

## Contesto
Il comportamento si verifica con l'ultima release v1.0.0-19.
Angular 16
